-- AR_ADDRESS represents both addresses as rows, differentiated by ADDRESS_TYPE:
--   PERMANENT and TEMPORARY.
-- Run this once against SAHYOG_DB after confirming the duplicate check returns no rows.

SELECT APPLICATION_NO, ADDRESS_TYPE, COUNT(*) AS ROW_COUNT
FROM AR_ADDRESS
GROUP BY APPLICATION_NO, ADDRESS_TYPE
HAVING COUNT(*) > 1;

ALTER TABLE AR_ADDRESS
    ADD CONSTRAINT UK_AR_ADDRESS_APPLICATION_TYPE
    UNIQUE (APPLICATION_NO, ADDRESS_TYPE);
